### ISSUE TITLE
Any troubles with 10.10 or greater?

### ISSUE THREAD

**Issue by jmartinez0837** [WardsParadox/Munki-Overnight#3]
Hey, sorry didnt know another way to get in contact with you. I still use my script version of the overnightMunki updates and im having an issue with it on Yosemite. It seems the LaunchDaemon is not running.

Are you having any issues with your python method on 10.10+?

**Comment by WardsParadox** [comment]
I haven't seen too many issues with LaunchD launching Python. I have noticed that this doesn't seem to stay awake at all since the removal of the lidwake. I didn't get the notification for this at all, sorry for the late response :sweat:

**Comment by jmartinez0837** [comment]
I am seeing a few issues after upgrading our devices to yosemite this
school year.

1: the pmset settings only work for turning on the machines at desired
time, not shutting them off. Apple decided to not shut off the computers if
they are at the log in screen. Thank you apple.
1. when computers do turn on, they are not running the script at the login
   screen. I know this bc they are not shutting off after its run. if i log in
   and run the script manually, everything works as its suppose to. if i
   unload and load the launchdaemon, nothing happens. maybe something is wrong
   with the launchd item? but it worked perfectly fine in 10.9.5

have any thoughts?

On Mon, Oct 19, 2015 at 4:27 PM, Zack McCauley notifications@github.com
wrote:

> I haven't seen too many issues with LaunchD launching Python. I have
> noticed that this doesn't seem to stay awake at all since the removal of
> the lidwake. I didn't get the notification for this at all, sorry for the
> late response [image: :sweat:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WardsParadox/Munki-Overnight/issues/3#issuecomment-149336838
> .

## 

Jeremy Martinez
Lower School Systems Manager
Riverdale Country School

**Comment by WardsParadox** [comment]
Referring to number 1: Instead of having the pmset to turn the devices off, just have the devices turn off at the end of the script with shutdown -h Now. That way you go around the login screen failing to shutdown.
Referring to number 2: I have been hearing this same thing on the macadmins slack team (this is a great resource to join as a Mac Admin). Is it as a launchagent or a launchdaemon? either way maybe add the key "RunOnLoad" that way if it is loaded it runs..make sure there is a time verifier to prevent running the full script at the time when they turn on the machines.

I'll check out the code and see if I can spot anything. Sorry I can't be too much more of help :sweat:

**Comment by WardsParadox** [comment]
Quickly glanced at the code, for number 2 you have both of the things I would recommend hmm..ya this might be a question for some of the other admins on the macadmins slack team. Plus your response answered some of my question ( I need more :coffee: ).

**Comment by jmartinez0837** [comment]
i figured it out. So it was a mistake on my part. I used my overnightMunki
launchd plist as a template for another launchd plist i needed and never
changed the "Label" key. so i had 2 launchd items with the same label.

All is still working now. My bad.

On Wed, Oct 21, 2015 at 10:38 AM, Zack McCauley notifications@github.com
wrote:

> Quickly glanced at the code, for number 2 you have both of the things I
> would recommend hmm..ya this might be a question for some of the other
> admins on the macadmins slack team. Plus your response answered some of my
> question ( I need more [image: :coffee:] ).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WardsParadox/Munki-Overnight/issues/3#issuecomment-149916978
> .

## 

Jeremy Martinez
Lower School Systems Manager
Riverdale Country School

**Comment by WardsParadox** [comment]
AH HA! :wink: 
Glad to know you got it fixed.
